export const FETCH_FORM_VALUES = "FETCH_FORM_VALUES";
export const FETCH_FORM_VALUES_SUCCESS = "FETCH_FORM_VALUES_SUCCESS";
export const FETCH_FORM_VALUES_FAILED = "FETCH_FORM_VALUES_FAILED";
export const SEND_FORM_VALUES = "SEND_FORM_VALUES";
export const SEND_FORM_VALUES_SUCCESS = "SEND_FORM_VALUES_SUCCESS";
export const SEND_FORM_VALUES_FAILED = "SEND_FORM_VALUES_FAILED";
